/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;


import javax.swing.JOptionPane;


/**
 *
 * @author mohan
 */
public class ISSUE extends javax.swing.JFrame {

    /**
     * Creates new form ISSUE
     */
    public ISSUE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel2.setText("RETURN DATE-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 210, 100, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setText("ISSUE DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 20, 220, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel4.setText("STUDENT P.I.D");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 100, 20);

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel8.setText("  [dd-mm]");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(230, 220, 80, 20);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 210, 40, 30);

        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(140, 260, 160, 30);

        jTextField6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(190, 160, 40, 30);

        jTextField7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(140, 110, 160, 30);

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 200, 130, 50);

        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton2.setText("ISSUE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 120, 130, 50);

        jTextField9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(190, 210, 40, 30);

        jTextField8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(140, 160, 40, 30);

        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(370, 40, 140, 50);

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel10.setText("ISSUE DATE-");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 160, 80, 20);

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel9.setText("BOOK ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 110, 80, 20);

        jLabel11.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel11.setText("  [dd-mm]");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 170, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/woman-nature.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-270, -80, 1060, 480);

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(540, 60, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Statement stmt = null;
    ResultSet rs = null;        // ResultSet for publisher table.
    String SQL = "SELECT * FROM issue";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  int i_date,r_date,i_month,r_month;
        i_date=Integer.parseInt(jTextField8.getText());
        i_month=Integer.parseInt(jTextField6.getText());

        if(i_date>=24){
            r_date=(i_date+7)-30;
            i_month++;
        }
        else{
            r_date=i_date+7;
        }
        r_month=i_month;
        jTextField1.setText(""+r_date);
        jTextField9.setText(""+r_month);
char isu_date;

        
        
        

   try{ Class.forName("com.mysql.jdbc.Driver");
         Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/liker","root","mohan");
            stmt = con.createStatement();
      
            rs = stmt.executeQuery(SQL);
           int pid=Integer.parseInt(jTextField2.getText());
            int book_id=Integer.parseInt(jTextField7.getText());
             int i_date_d=Integer.parseInt(jTextField8.getText());
            int i_date_m=Integer.parseInt(jTextField6.getText());
            int r_date_d=r_date;
            int r_date_m=r_month;
            
              int code = JOptionPane.showConfirmDialog(this, "check details?", "Confirmation Dialog Box", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (code == JOptionPane.YES_OPTION) {
                
                
                
                
                String strSQL = "INSERT INTO issue(isssue_id, pid, i_date,r_date) VALUES ('"+book_id+"', '"+pid+"', '"+i_date_d+"','"+r_date_d+"')";
                 int rowsEffected = stmt.executeUpdate(strSQL); 
                JOptionPane.showMessageDialog(this, "Record added successfully ");
                                                }
    }
   catch(Exception e){
   
   JOptionPane.showMessageDialog(this, e);
   
   }
   
       


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:jTextField2.setText("");
        jTextField7.setText("");jTextField1.setText("");jTextField2.setText("");jTextField6.setText("");jTextField8.setText("");jTextField9.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISSUE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
