/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mohan
 */
public class RETURN extends javax.swing.JFrame {

    /**
     * Creates new form ISSUE
     */
    public RETURN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel2.setText("RETURN DATE-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 160, 80, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel3.setText("RETURN DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 10, 220, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel4.setText("STUDENT P.I.D");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 200, 100, 20);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel5.setText("BOOK ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 80, 20);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel6.setText("DAYS LATE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 280, 80, 20);

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel7.setText("CHARGES ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 320, 80, 20);

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel8.setText("TODAYS DATE-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 80, 100, 20);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 150, 160, 30);

        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 190, 160, 30);

        jTextField3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 230, 160, 30);

        jTextField4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField4.setEnabled(false);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(120, 270, 160, 30);

        jTextField5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField5.setEnabled(false);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(120, 310, 160, 30);

        jTextField6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField6.setEnabled(false);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(120, 110, 160, 30);

        jTextField8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(150, 70, 40, 30);

        jTextField7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(200, 70, 40, 30);

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 290, 150, 50);

        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton2.setText("RESET");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(410, 210, 150, 50);

        jButton3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton3.setText("RETURN");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(410, 120, 150, 50);

        jButton5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton5.setText("DISPLAY DETAILS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(400, 40, 160, 50);

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jLabel9.setText("ISSUE DATE-");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 120, 80, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/samurai.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-70, -20, 830, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

             Statement stmt = null;
            ResultSet rs = null;
            String SQL = "SELECT * FROM issue";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:jTextField2.setText("");
 jTextField6.setText("");       jTextField3.setText("");jTextField5.setText("");jTextField4.setText("");jTextField1.setText("");jTextField2.setText("");
 jTextField2.setEnabled(true);
jTextField3.setEnabled(true);
jTextField7.setEnabled(true);
jTextField8.setEnabled(true);
  jButton5.setEnabled(true);
  jButton3.setEnabled(false); jButton2.setEnabled(false);
  jTextField7.setText(""); jTextField8.setText(""); 
 
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

         
        jButton5.setEnabled(false);
  jButton3.setEnabled(true);
   jButton2.setEnabled(true);
jTextField1.setEnabled(false);
jTextField2.setEnabled(false);
jTextField3.setEnabled(false);
jTextField4.setEnabled(false);
jTextField5.setEnabled(false);
jTextField6.setEnabled(false);

jTextField8.setEnabled(false);
jTextField7.setEnabled(false);

int pid=Integer.parseInt(jTextField2.getText());
int a=pid;
String query="select * from issue where pid="+a+";";       
        
        
       try{
     Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Liker","root","mohan");
              stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            
             if (rs.next()) {

               int book_id = rs.getInt("isssue_id"); 
              int i_date = rs.getInt("i_date"); 
              int r_date = rs.getInt("r_date"); 
               
              
            
               
                    jTextField3.setText(""+book_id);
                    jTextField6.setText(""+i_date);
                    jTextField1.setText(""+r_date);
             }
               else {
                JOptionPane.showMessageDialog(null, "Record does not found in books table");
                
                      }
    
}catch(Exception e){ JOptionPane.showMessageDialog(this, e.getMessage()); 
}
       
 int today=Integer.parseInt(""+jTextField8.getText());
 int issue_date=0;
 int return_date=0;
 int charges,days_late=0,i=0;
 
issue_date=Integer.parseInt(jTextField6.getText()); 
return_date=Integer.parseInt(jTextField1.getText());
if(return_date>today)
{
days_late=0;
}
else if(return_date<=30&&today<=30)
{
    days_late=today-return_date;
}

jTextField4.setText(""+days_late);





 charges= days_late*5;
 jTextField5.setText(""+charges);

       
       
       
       
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{

        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/liker","root","mohan");
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
           int pid=Integer.parseInt(jTextField2.getText());
            
            
            String strSQL = "delete from issue where pid ='"+pid+"';";
            int rowsEffected = stmt.executeUpdate(strSQL);
            if (rowsEffected == 0)
                JOptionPane.showMessageDialog(this, "Record does not exists");
            else
                  JOptionPane.showMessageDialog(this,"Book returned sucessfully!!");
}
catch(Exception e){



}




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RETURN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RETURN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
