
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author mohan
 */
public class UPDATE_BOOKS extends javax.swing.JFrame {

    /**
     * Creates new form BOOKS
     */
    public UPDATE_BOOKS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
             Statement stmt = null;
            ResultSet rs = null;
            String SQL = "SELECT * FROM books";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 10)); // NOI18N
        jLabel2.setText("BOOK ID  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 70, 26);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel3.setText("UPDATE BOOK DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 270, 26);

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 10)); // NOI18N
        jLabel4.setText("BOOK NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 70, 26);

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 0, 10)); // NOI18N
        jLabel5.setText("AUTHOR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 200, 70, 26);

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 0, 10)); // NOI18N
        jLabel6.setText("GENERE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 250, 70, 26);

        jButton1.setBackground(new java.awt.Color(78, 2, 2));
        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 270, 90, 40);

        jButton2.setBackground(new java.awt.Color(79, 0, 0));
        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 40, 90, 40);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(100, 150, 240, 30);

        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(100, 200, 240, 30);

        jTextField3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jTextField3.setEnabled(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(100, 250, 240, 30);

        jTextField4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 10)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(100, 100, 240, 30);

        jButton3.setBackground(new java.awt.Color(79, 0, 0));
        jButton3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 110, 90, 40);

        jButton4.setBackground(new java.awt.Color(79, 0, 0));
        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 10)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(460, 190, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crystall.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-710, -880, 2330, 1370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jButton2.setEnabled(false);
jTextField1.setEnabled(true);
jTextField2.setEnabled(true);
jTextField3.setEnabled(true);
jTextField4.setEnabled(false);
int book_id=Integer.parseInt(jTextField4.getText());
int a=book_id;
String query="select * from books where book_id="+a+";";

try{
     Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Liker","root","mohan");
              stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            
             if (rs.next()) {

                String book_name = rs.getString("book_name");
                String genere = rs.getString("genere");
                String author = rs.getString("author");
              
            
                    jTextField1.setText(book_name);
                    jTextField2.setText(author);
                    jTextField3.setText(genere);
             }
               else {
                JOptionPane.showMessageDialog(null, "Record does not found in books table");
                
                      }
    
}catch(Exception e){ JOptionPane.showMessageDialog(this, e.getMessage()); 
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        
        jTextField4.setEnabled(true);jTextField3.setEnabled(false);jTextField2.setEnabled(false);jTextField1.setEnabled(false);
        jButton2.setEnabled(true);
        jTextField2.setText("");
        jTextField3.setText("");jTextField4.setText("");jTextField1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/liker","root","mohan");
            stmt = con.createStatement();
            rs = stmt.executeQuery(SQL);
           int book_id=Integer.parseInt(jTextField4.getText());
            String book_name=jTextField1.getText();
            String author=jTextField2.getText();
            String genere=jTextField3.getText();
            
            String strSQL = "Update books set book_name ='"+(book_name)+"', author = '"+(author)+"', genere = '"+(genere)+ "'where book_id = '" + (book_id)+"';";
            int rowsEffected = stmt.executeUpdate(strSQL);
            if (rowsEffected == 0)
                JOptionPane.showMessageDialog(this, "Record does not exists");
            else
                JOptionPane.showMessageDialog(this,"Record updated sucessfully!!");
 }catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());
    }
  
      
            
                                        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATE_BOOKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATE_BOOKS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
